AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Demogo-multitenancy
Resources:
    Authtemplate:
      Type: AWS::Serverless::Application
      Properties:
        Location: auth.yaml
    Apitemplate:
      Type: AWS::Serverless::Application
      Properties:
        Location: api.yaml  

